"""Fig 11 -- Stage 2b synthetic benchmark: band-FRC stratified by scene noise
and scene delta-T (ACL-054/ACL-060).

Context: Stage 2b is the held-out synthetic benchmark (48 scenes, seed
20260912, "pool_2x_v8_bench48", never trained on) built specifically to
separate two explanations for the neural-vs-TGV gap seen on real data:
H1 (synthetic-to-real domain gap -- the learned prior does not transfer)
vs. H2 (architecture ceiling -- the network leaves information on the
table even in-domain). It was the first time TGV/MAP-TV, the classical
physics baselines, were ever evaluated on our own synthetic generator, so
their synthetic-domain numbers are a genuinely new reference point, not a
re-plot of something already known.

This figure stratifies the headline metric (band-limited FRC vs. GT,
25-40 micron band, at the full N=96-frame burst) by two scene covariates
that are resampled per synthetic scene: the injected read/shot noise
level (noise_tertile: lo/mid/hi) and the scene's radiometric contrast
(delta_T_tertile: lo/mid/hi, degrees C). Panel (a) is the noise axis,
panel (b) is the delta-T axis. Each tertile bin contains n=16 scenes;
error bars are standard error of the mean (std / sqrt(16)) computed from
the per-scene metric distribution.

Arms shown are exactly the six carrying rows in the Stage 2b main table
(research_log/algorithm_changelog.md ACL-054): the two TGV drizzle-prior
variants (oracle = true per-frame shift, portable = estimated shift),
MAP-TV oracle as a second classical baseline, and three neural arms
spanning the eta (data-fit weight) design space explored around the
champion search: v14 (high eta = evidence-heavy prior, best raw
synthetic FRC but known large low-frequency drift on held-out data),
v19_etaB (low eta = prior-heavy, the arm selected as the real-domain
robustness champion), and v20_champion (a nominal "combined-loss"
checkpoint from the aborted 50k champion run that ACL-054 determined
post hoc to be a corrupted snapshot -- its whole spectrum is wrong, not
just a mild regression -- confirmed independently by its sub-baseline
score on its own training scenes). It is left in the figure deliberately
as the case study that motivated the process rule "every new checkpoint
gets a synthetic-benchmark health check before anything else."

Data provenance (read-only, not regenerated by this script):
  remote_inbox/20260711_stage2b/stage2b_stratified_noise.csv
  remote_inbox/20260711_stage2b/stage2b_stratified_deltaT.csv
  Both are 3-row MultiIndex-header pivot tables (arm, n_frames_used,
  <tertile> | metric, {mean,std}) produced by
  algos/ep07_unet_sr/scripts/run_stage2b_synth_benchmark.py's aggregation
  stage (ACL-054/ACL-060). stage2b_summary.csv / stage2b_long.csv in the
  same directory were inspected as a fallback / cross-check path but were
  not needed -- the stratified CSVs are directly usable.

Run:
  cd /Users/ujs/mycode/thermal_lift && uv run python docs/publication_figures/scripts/fig11_stage2b_stratified.py
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from pubfig_style import REPO_ROOT, W_1P5, save_fig, setup_academic_style

setup_academic_style()

DATA_DIR = REPO_ROOT / "remote_inbox" / "20260711_stage2b"
N_FRAMES = 96          # full burst -- best-converged, least-noisy condition
N_SCENES_PER_TERTILE = 16
METRIC = "frc_band_mean_25_40"

# ── Load stratified pivot tables (3-row header: metric / stat / blank) ─────
noise_df = pd.read_csv(DATA_DIR / "stage2b_stratified_noise.csv", header=[0, 1, 2])
dt_df = pd.read_csv(DATA_DIR / "stage2b_stratified_deltaT.csv", header=[0, 1, 2])

# Flatten the id columns (arm / n_frames_used / tertile) and the metric
# columns (frc_band_mean_25_40, mean|std) into plain names.
def tidy(df: pd.DataFrame, tertile_col: str) -> pd.DataFrame:
    out = pd.DataFrame({
        "arm": df[("Unnamed: 0_level_0", "Unnamed: 0_level_1", "arm")],
        "n_frames_used": df[("Unnamed: 1_level_0", "Unnamed: 1_level_1", "n_frames_used")],
        "tertile": df[("Unnamed: 2_level_0", "Unnamed: 2_level_1", tertile_col)],
        "mean": df[(METRIC, "mean", "Unnamed: 7_level_2")],
        "std": df[(METRIC, "std", "Unnamed: 8_level_2")],
    })
    out["sem"] = out["std"] / np.sqrt(N_SCENES_PER_TERTILE)
    return out

noise_df = tidy(noise_df, "noise_tertile")
dt_df = tidy(dt_df, "delta_T_tertile")

# ── Fixed arm -> style mapping ──────────────────────────────────────────
# TGV pair: fixed grays per brief. MAP-TV: classical baseline, reused taupe
# style from pubfig_style.METHOD_STYLE. Neural trio: blue/red/green from the
# specified 4-color neural family, in main-table order (purple slot unused --
# only 3 neural arms are in the Stage 2b headline table).
ARMS = {
    "tgv__oracle":    dict(color="#333333", marker="s", ls="-",  label="TGV (oracle)"),
    "tgv__portable":  dict(color="#888888", marker="s", ls="--", label="TGV (portable)"),
    "maptv__oracle":  dict(color="#937860", marker="D", ls=":",  label="MAP-TV (oracle)"),
    "v14":            dict(color="#4C72B0", marker="o", ls="-",  label=r"Neural v14 ($\eta$=0.5)"),
    "v19_etaB":       dict(color="#C44E52", marker="^", ls="-",  label=r"Neural v19 ($\eta$=0.09)"),
    "v20_champion":   dict(color="#55A868", marker="x", ls="-.", label="Neural v20 (corrupted ckpt)"),
}

NOISE_ORDER = ["lo", "mid", "hi"]
NOISE_LABELS = ["Low\n($\\sigma\\approx$0.05)", "Mid\n($\\sigma\\approx$0.07)", "High\n($\\sigma\\approx$0.10)"]
DT_ORDER = ["lo", "mid", "hi"]
DT_LABELS = ["Low\n($\\approx$1.5 $^{\\circ}$C)", "Mid\n($\\approx$3.2 $^{\\circ}$C)", "High\n($\\approx$4.3 $^{\\circ}$C)"]

fig, (ax_a, ax_b) = plt.subplots(1, 2, figsize=(W_1P5, 2.8), sharey=True)

def plot_panel(ax, df, order):
    sub_n = df[df["n_frames_used"] == N_FRAMES]
    for arm, st in ARMS.items():
        sub = sub_n[sub_n["arm"] == arm].set_index("tertile")
        y = np.array([sub.loc[t, "mean"] for t in order])
        e = np.array([sub.loc[t, "sem"] for t in order])
        x = np.arange(len(order))
        ax.errorbar(x, y, yerr=e, color=st["color"], marker=st["marker"], ls=st["ls"],
                     label=st["label"], markersize=4.5, capsize=2, lw=1.3,
                     elinewidth=0.8, clip_on=False)

plot_panel(ax_a, noise_df, NOISE_ORDER)
ax_a.set_xticks(range(len(NOISE_ORDER)))
ax_a.set_xticklabels(NOISE_LABELS)
ax_a.set_xlabel("Scene noise tertile")
ax_a.set_title("(a) By noise level", loc="left")

plot_panel(ax_b, dt_df, DT_ORDER)
ax_b.set_xticks(range(len(DT_ORDER)))
ax_b.set_xticklabels(DT_LABELS)
ax_b.set_xlabel(r"Scene $\Delta T$ tertile")
ax_b.set_title("(b) By scene contrast", loc="left")

ax_a.set_ylabel("Band-FRC vs. GT, 25–40 $\\mu$m [mean $\\pm$ SEM]")
ax_a.set_ylim(0.0, 1.0)
for ax in (ax_a, ax_b):
    ax.margins(x=0.15)

handles, labels = ax_a.get_legend_handles_labels()
fig.legend(handles, labels, loc="lower center", ncol=3, bbox_to_anchor=(0.5, -0.16),
           fontsize=7.2, columnspacing=1.0, handletextpad=0.4, frameon=False)

paths = save_fig(fig, "fig11_stage2b_stratified")
print("\n".join(str(p) for p in paths))
