"""TCForge core library for ThermalChipPhantom synthetic data generation."""

from __future__ import annotations

from .classical_sr import drizzle_features, drizzle_features_4x, phase_bin_drizzle, shift_and_add
from .forward import FORWARD_MODES, generate_lr_burst, physical_block_average_forward
from .fusion import fuse_burst_to_features
from .geometry import (
    CANVAS_SHAPE_4X,
    SCALE_4X,
    apply_edge_diffusion,
    build_multi_temp_mask,
    build_multi_temp_mask_with_metadata,
    build_scene_mask,
    build_scene_mask_with_metadata,
    composite,
    make_circle_pad,
    make_cross,
    make_ellipse_pad,
    make_frame,
    make_l_shape,
    make_pin_array,
    make_rectangle,
    make_trenches,
    make_via_array,
    rotate_mask,
)
from .highpass import highpass_preprocess
from .manifest import SceneManifest
from .evaluate import (
    aggregate_scene_metrics,
    binary_iou,
    boundary_f1,
    evaluate_dataset,
    evaluate_scene,
    finite_summary,
    mae,
    masked_mae,
    masked_rmse,
    nrmse,
    psnr,
    rmse,
    split_half_drizzle_consistency,
    split_half_drizzle_consistency_scene,
    summarize_scene,
)
from .physics import (
    add_detector_defects,
    add_noise,
    apply_drift,
    apply_psf_blur,
    edge_map,
    make_noise,
    make_psf_kernel,
    render_temperature_field,
    sample_physics_parameters,
    sample_psf_parameters,
    temporal_trend_drift,
)
from .reconstruct import reconstruct_hr_temperature
from .shifts import (
    SHIFT_CONVENTION,
    build_scene_shifts,
    ideal_phase_grid,
    load_shift_profile,
    random_constellation,
)
from .storage import COMPACT_SCENE_FILES, load_scene_compact, save_scene_compact

__version__ = "0.1.0"

__all__ = [
    "CANVAS_SHAPE_4X",
    "COMPACT_SCENE_FILES",
    "FORWARD_MODES",
    "SCALE_4X",
    "SHIFT_CONVENTION",
    "SceneManifest",
    "__version__",
    "add_detector_defects",
    "add_noise",
    "aggregate_scene_metrics",
    "apply_edge_diffusion",
    "apply_drift",
    "apply_psf_blur",
    "binary_iou",
    "boundary_f1",
    "build_multi_temp_mask",
    "build_multi_temp_mask_with_metadata",
    "build_scene_mask",
    "build_scene_mask_with_metadata",
    "build_scene_shifts",
    "composite",
    "edge_map",
    "evaluate_dataset",
    "evaluate_scene",
    "finite_summary",
    "fuse_burst_to_features",
    "generate_lr_burst",
    "highpass_preprocess",
    "ideal_phase_grid",
    "drizzle_features",
    "drizzle_features_4x",
    "load_scene_compact",
    "load_shift_profile",
    "mae",
    "masked_mae",
    "masked_rmse",
    "make_circle_pad",
    "make_cross",
    "make_ellipse_pad",
    "make_frame",
    "make_l_shape",
    "make_noise",
    "make_pin_array",
    "make_psf_kernel",
    "make_rectangle",
    "make_trenches",
    "make_via_array",
    "nrmse",
    "phase_bin_drizzle",
    "physical_block_average_forward",
    "psnr",
    "random_constellation",
    "reconstruct_hr_temperature",
    "render_temperature_field",
    "rmse",
    "rotate_mask",
    "sample_physics_parameters",
    "sample_psf_parameters",
    "save_scene_compact",
    "shift_and_add",
    "split_half_drizzle_consistency",
    "split_half_drizzle_consistency_scene",
    "summarize_scene",
    "temporal_trend_drift",
]
